openapi: 3.0.2
info: 
 title: "sample worker's api for job queue 'fireworq'"
 version: 0.0.1
servers: 
- url: http://localhost:8080
  description: "development server"
paths:
 /works:
  post:
   description: お仕事する
   operationId: postWorks
   requestBody:
    $ref: '#/components/requestBodies/Issues'
   responses:
    '200':
     $ref: '#/components/responses/PostResponse'
components:
  schemas:
    PostRequests:
     type: object
     properties:
       id:
        type: integer
        example: 1
       contents:
        type: string
        example: "issue's description"
    PostResponse:
     type: object
     properties:
       status:
        type: string
        example: "success"
       message:
        type: string
        example: "It's working!"
  requestBodies:
    Issues:
     description: 処理するIssue
     required: true
     content:
       application/json:
        schema:
          $ref: '#/components/schemas/PostRequests'
  responses:
    PostResponse:
      description: 処理の実行結果
      content:
        application/json:
         schema:
           $ref: '#/components/schemas/PostResponse'